name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@main

      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # react build
        run: npm run build
